server:
  port: 8080

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
zuul:
  ignored-services: '*' # routes에 정의되지 않은 모든 요청은 무시
  routes:
    user-producer:
      path: /api/v1/prod/**     # 사용자가 입력할 url
      service-id: USER-PRODUCER # routing을 처리할 엔드포인트 서비스
      strip-prefix: true        # path에서 /** 앞의 경로는 제거 후 뒷단 서비스로 요청 함