server:
  port: 8080

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  ignored-services: '*'         # routes에 정의되지 않은 모든 요청은 무시
  prefix: /api/v1               # routes에 정의된 모든 서비스의 엔드포인트를 /api/v1/~ 으로 묶음
  routes:
    user-producer:
      path: /prod/**            # 사용자가 입력할 url
      service-id: user-producer # routing을 처리할 엔드포인트 서비스 (아래에서 정의) - 로드밸런싱을 위해 url이 아닌 service-id를 적는다.
      strip-prefix: true        # path에서 /** 앞의 경로는 제거 후 뒷단 서비스로 요청 함
